openapi: 3.0.2
info:
  title: Hiko API
  version: 1.0.0
  x-logo:
    altText: Hiko logo
  description: |
    # Introduction
    ### Hiko API Document for shop

    * Welcome to the Hiko API! You can use our API to access Hiko API endpoints, which can get information on
    various trackings, businesses and payments in our database.

    * We have language bindings in HTTP and you can view code examples in the dark area to the right.

    _As you scroll, you'll see code examples for working with the API in different programming languages in the dark area
    to the right (or as part of the content on mobile). You can switch the language used with the tabs at the top right
    (or from the nav menu at the top left on mobile)._

    The portal provides documentation for the following APIs and services:
    * [Package API](#tag/Package). Create delivery orders, generate waybills, and cancel orders.
    * [Location API](#tag/Location). Get location informations.

    All Hiko APIs are RESTful APIs.

    ## Base URL by environment
      ### Production base URL
      * URL: `https://{parter-code}.gateway.hikolog.vn`

      ### Staging base URL
      * URL: `https://stg-{parter-code}.gateway.hikolog.vn`

      **Note:** {parter-code} will be received via contract or integration directly

    ## Rate limiting
      In order to provide a high-quality of service for all customers, our API is rate limited.
      If the rate limit is exceeded, the API responds with an HTTP `400 API rate limit exceeded` status code, and you get temporarily blocked from accessing the API.
      In this case, retry your request after a few hours.
tags:
  - name: Authentication
    description: |-
      Returns a new Bearer access token.

      ### Prerequisites

      To make requests to this endpoint, you need to have the Email and Password. You can obtain by registration new account here:
      1. Production: shop.hikolog.vn
      2. Staging: stg-shop.hikolog.vn

      ### Implementation flow

      Your implementation must adhere to this flow:
      1. Login and get the access_token.
      2. Store the token, along with the expiration timestamp, in a persistent storage.
      3. Attach the token as a Bearer token with every API request to a Hiko API. This means that for the `Authorization` HTTP header, the value must be `Bearer <INSERT ACCESS TOKEN>`.
      4. This token is live forever
  - name: Package
    description: The purpose of the Package API is to create delivery orders, generate awb, and cancel orders...
  - name: Location
    description: |-
      Show address with port codes.

      You can download our address tree here: https://hiko-logistic.github.io/api-gateway-doc/assets/Address_12_2023.csv
  - name: WareHouse
    description: Create/Update warehouse
  - name: Webhooks
    description: |-
      Webhooks help you register to listen to events arising from Quick.vn's system, for example:
      - Receive package status change
      - Package has dim weight changed
      ## Webhook events
        | Event                                 | Webhook is triggered when... |
        |---------------------------------------|------------------------------|
        | Package status                        | Update status package        |
        | Package re-weight                     | Update package dim weight    |

      ## Receive a Webhook
      ### Sample webhook payloads
      #### package status
       | Fields                                |  Type               |             Notes            |
       |---------------------------------------|---------------------|------------------------------|
       | type                                  |  String             | required                     |
       | code                                  |  String             | required                     |
       | status                                |  String             | required                     |
       | epod                                  |  String             |                              |
       | reason                                |  String             |                              |
       | trace_id                              |  String             |                              |

          {
              "type": "package-update-status",
              "code": "PKG2210897312",
              "reason": "recipient reschedule",
              "epod": "https://domain.com/url-to-epod-image-here",
              "status": "Delivery_failed_attempt"
          }

      #### package re-weight
       | Fields                                |  Type               |             Notes            |
       |---------------------------------------|---------------------|------------------------------|
       | type                                  |  String             | required                     |
       | code                                  |  String             | required                     |
       | length                                |  float              | required                     |
       | width                                 |  float              | required                     |
       | height                                |  float              | required                     |
       | weight                                |  float              | required                     |
       | trace_id                              |  String             | required                     |

          {
              "type": "package-re-weight",
              "code": "PKG2210897312",
              "length": 10.02,
              "width": 12.01,
              "height": 8.2,
              "weight": 2.5
          }

servers:
  - url: //{partner-code}-gateway.hikolog.vn/api/
    description: Production server
  - url: //stg-{partner-code}-gateway.hikolog.vn/api/
    description: Staging server

paths:
  # ---------------------  Authentication --------------------------------------
  /login:
    post:
      tags:
        - Authentication
      summary: Login
      operationId: login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_login_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginError'

  /profile:
    get:
      tags:
        - Authentication
      summary: Get Profile
      operationId: get_profile
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileRes'
      security:
        - APIKeyHeader: []

  /logout:
    delete:
      tags:
        - Authentication
      summary: Logout
      operationId: logout_delete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutBody'

      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTrue'
      security:
        - APIKeyHeader: []

  # ---------------------  Package --------------------------------------
  /packages:
    get:
      tags:
        - Package
      summary: Get All Packages
      operationId: get_all_packages
      parameters:
        - name: Authorization
          in: header
          description: Your Bearer token.
          required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAllPackages"
      security:
        - APIKeyHeader: []

  /packages/{code}:
    get:
      tags:
        - Package
      summary: Show Package
      operationId: show_package
      parameters:
        - required: true
          schema:
            title: Package code
            type: string
          name: package-code
          in: path
          example: BAM291120019982
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackageOut"
        '422':
          description: Validation Error
          content:
            application/json:
              schema: {}
      security:
        - APIKeyHeader: []

  /packages/:
    post:
      tags:
        - Package
      summary: Create Package
      operationId: create_package
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PackageCreate"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackageOut"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatePackageError"
      security:
        - APIKeyHeader: []


  /shipping-fees:
    post:
      tags:
        - Package
      summary: Get Shipping Fees
      operationId: Get Shipping Fees
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BodyGetShippingFees"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseGetShippingFees"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseGetShippingFeesError"
      security:
        - APIKeyHeader: []

  /insurance-fees:
    post:
      tags:
        - Package
      summary: Get Insurance Fees
      operationId: Get Insurance Fees
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BodyInsuranceFees"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseInsuranceFee"
      security:
        - APIKeyHeader: [ ]

  /packages/{code}/history:
    get:
      tags:
        - Package
      summary: Package Tracking History
      operationId: package_tracking_history
      parameters:
        - required: true
          schema:
            title: Package code
            type: string
          name: code
          in: query
          example: BAM291120019982
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponsePackageHistory"
        '422':
          description: Validation Error
          content:
            application/json:
              schema: {}
      security:
        - APIKeyHeader: []

  /package-statuses:
    get:
      tags:
        - Package
      summary: Get All Package Statuses
      operationId: get_all_package_statuses
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageStatuses'
      security:
        - APIKeyHeader: []

  /packages-cancel/{code}:
    patch:
      tags:
        - Package
      summary: Cancel Package
      operationId: cancel_package
      parameters:
        - required: true
          schema:
            title: Package code
            type: string
          name: code
          in: path
          example: BAM291120019982
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTrue'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseFailed'
      security:
        - APIKeyHeader: []

  /packages-print-awb:
    post:
      tags:
        - Package
      summary: Get Package Awb
      operationId: get_package_awb
      requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PayLoadAwb"
          required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseAwb"
      security:
        - APIKeyHeader: []

  # ---------------------  Location  --------------------------------------
  /addresses:
    get:
      tags:
        - Location
      summary: Get ThreePL address
      operationId: get_threepl_address
      parameters:
        - required: true
          schema:
            title: limit
            type: integer
          name: limit
          in: path
          example: 10
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreePLAddress'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseFailed'
      security:
        - APIKeyHeader: []

  /warehouse:
    post:
      tags:
        - WareHouse
      summary: Create WareHouse
      operationId: Create WareHouse
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PayloadStore"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStore'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseFailed'
      security:
        - APIKeyHeader: [ ]

  /warehouse/{code}:
    get:
      tags:
        - WareHouse
      summary: Get WareHouse By Code
      operationId: get_warehouse_by_code
      parameters:
        - required: true
          schema:
            title: code
            type: string
          name: code
          in: path
          example: WH000001
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStore'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseFailed'
      security:
        - APIKeyHeader: [ ]


  /warehouse/{code}/:
    patch:
      tags:
        - WareHouse
      summary: Update WareHouse By Code
      operationId: update_warehouse_by_code
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PayloadUpdateStore"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseStore'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseFailed'
      security:
        - APIKeyHeader: [ ]



components:
  schemas:

    Body_login_post:
      title: Body_login_post
      required:
        - email
        - password
      type: object
      properties:
        email:
          title: Email
          type: string
        password:
          title: Password
          type: string

    Token:
      title: Token
      type: object
      properties:
        success:
          title: True/False
          type: boolean
        access_token:
          title: Access Token
          type: string
      example:
        success: true
        access_token: 37|fzN5sMtrRKmy4VSXK1jwJqbnkttCsJ3aJFwfA8mp

    LoginError:
      title: LoginError
      type: object
      properties:
        error:
          type: string
          example: The provided credentials are incorrect.

    LogoutBody:
      title: LogoutBody
      required:
        -  Authorization
      type: object
      properties:
        Authorization:
          title: bearer
          type: string
          example: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9

    PayLoadAwb:
      title: Print Awb
      required:
        - codes
      type: object
      properties:
        codes:
          title: codes
          type: array
          description: The codes can be used as code or package_code
          example: ["PKG0302660748","PKG2210897312"]
        type:
          title: type
          type: string
          description: 'There are two types: <ul><li>**pdf**: Return PDF file</li><li>**link**: Return link AWB</li></ul>Type "**pdf**" will be the default option if "type" not provided'
          example: "link"

    Items:
      required:
        - item_description
      type: object
      properties:
        name:
          maxLength: 255
          type: string
          description: The name of the item.
        quantity:
          type: number
          description: Quantity of the item.
        amount:
          type: number
          description: Amount of the item.
        weight:
          type: number
          description: Weight (kg) of the item.
      description: Details of the items.

    PackageCreate:
      title: PackageCreate
      required:
        - code
        - cod
        - weight
        - size_l
        - size_h
        - size_w
        - receiver_name
        - receiver_phone
        - product_value
        - is_insurance_fee
        - receiver_address
        - receiver_port_code
        - sender_address
        - sender_port_code
        - notes
        - quantity
      type: object
      properties:
        code:
          title: Code
          type: string
        cod:
          title: Cash on Devliery - COD
          type: integer
        weight:
          title: Weight
          type: integer
        size_l:
          title: Length
          type: integer
        size_h:
          title: Height
          type: integer
        size_w:
          title: Width
          type: integer
        product:
          title: Product
          type: string
        package_products:
          title: Product
          type: array
          items:
            $ref: '#/components/schemas/Items'
        product_value:
          title: Product value
          type: integer
        is_insurance_fee:
          title: Is Insurance Fee (product value > 3000000, insurance = productValue*0.005)
          type: boolean
        receiver_name:
          title: Receiver's name
          type: string
        receiver_phone:
          title: Receiver's phone
          type: string
        receiver_address:
          title: Receiver's address
          type: string
        receiver_port_code:
          title: Receiever's port code
          type: string
        sender_address:
          title: Sender's address
          type: string
        sender_port_code:
          title: Sender's port code
          type: string
        notes:
          title: Note
          type: string
        quantity:
          title: quantity
          type: integer
        address_type:
          title: address_type
          type: string
          default: work
          description: value "home" or "work"
        sender_payment:
          title: sender_payment
          type: boolean
          default: true
          description: "true: Sender pay fee; false: Receiver pay fee"
        delivery_options:
          title: delivery_options
          type: integer
          default: 1
          description: "1: can open, try product is not allowed  or  2: Not co-checked"
      example:
        code: "PKG2210897312"
        cod: 7000000
        weight: 10
        size_l: 20
        size_h: 30
        size_w: 30
        product: "Iphone 14 Promax"
        package_products:
          - amount: 10000000
            name: Laptop
            quantity: 1
            weight: 1.3
          - amount: 30000000
            name: Macbook
            quantity: 1
            weight: 0.5
        product_value: 40000000
        insurance_fee: 20000
        is_insurance_fee: true
        receiver_name: "Tran Van A"
        receiver_phone: "090 9332 982"
        receiver_address: "81 Hoàng Minh Giám"
        receiver_port_code: "R2587289"
        sender_address: "5/34 Thủ Khoa Huân"
        sender_port_code: "R2587289"
        notes: "Hàng dễ vỡ, xin nhẹ tay"
        quantity: 1



    PayloadStore:
      title: CreateStore
      required:
        - address_port_code
        - address
      properties:
        name:
          type: string
          title: name
          minLength: 3
          example: "Shop em bé"
          description: This field is optional, if not provided, seller's name will be used
        phone:
          type: number
          title: phone
          minLength: 10
          maxLength: 11
          example: "0987234211"
          description: This field is optional, if not provided, seller's phone will be used
        address:
          type: string
          title: address
          example: "132A Nguyễn Trọng Tuyển"
        address_port_code:
          type: string
          title: address_port_code
          example: "R000911"

    PayloadUpdateStore:
      title: CreateStore
      properties:
        name:
          type: string
          title: name
          minLength: 3
          example: "Shop em bé"
        phone:
          type: number
          title: phone
          minLength: 10
          maxLength: 11
          example: "0987234211"
        address_port_code:
          type: string
          title: address_port_code
          example: "R000911"
        address:
          type: string
          title: address
          example: "132A Nguyễn Trọng Tuyển"

    ResponseStore:
      title: Response Store
      type: object
      properties:
        warehouse_code:
          type: string
          default: "WH000001"
        phone:
          type: string
          default: "0987234211"
        address:
          type: string
          default: "132A Nguyễn Trọng Tuyển"
        ward:
          type: string
          default: "Phường 8"
        district:
          type: string
          default: "Quận Phú Nhuận"
        province:
          type: string
          default: "Thành Phố Hồ Chí Minh"

    ResponseGetAllStore:
      title: Response Get All Store
      type: object
      properties:
        warehouse_code:
          type: string
        address:
          type: string
        ward:
          type: string
        district:
          type: string
        Province:
          type: string


    PackageOut:
      title: PackageOut
      type: object
      properties:
        package_code:
          title: Hiko code
          type: string
        tracking_code:
          title: 3PL Tracking code
          type: string
        port_code:
          title: Port code
          type: string
        cod:
          title: Cod
          type: integer
        weight:
          title: Weight
          type: integer
        size_l:
          title: Size length
          type: integer
        size_h:
          title: Size height
          type: integer
        size_w:
          title: Size width
          type: integer
        product:
          title: Product
          type: string
        shiping_fee:
          title: Shipping fee
          type: integer
        product_value:
          title: Product value
          type: integer
        is_insurance_fee:
          title: Is Insurance Fee
          type: boolean
        insurance_fee:
          title: Insurance Fee
          type: integer
        receiver_name:
          title: Receiver's name
          type: string
        receiver_phone:
          title: Receiver's phone
          type: string
        receiver_address:
          title: Receiver address
          type: string
        receiver_port_code:
          title: Receiver port code
          type: string
        receiver_address_level_1:
          title: Receiever address lv1
          type: string
        receiver_address_level_2:
          title: Receiever address lv2
          type: string
        receiver_address_level_3:
          title: Receiever address lv3
          type: string
        sender_phone:
          title: Sender Phone
          type: string
        sender_email:
          title: Sender Email
          type: string
        sender_name:
          title: Sender Name
          type: string
        sender_address:
          title: Sender's address
          type: string
        sender_port_code:
          title: Sender's port code
          type: string
        sender_address_level_1:
          title: Sender's address lv1
          type: string
        sender_address_level_2:
          title: Sender's address lv2
          type: string
        sender_address_level_3:
          title: Sender's address lv3
          type: string
        status:
          title: Status
          type: string
        notes:
          title: Note
          type: string
      example:
        code: "PKG2210897312"
        package_code: "PKG10897312"
        tracking_number: "LMP0170517004VNA"
        port_code: "HT-TRG-I"
        cod: 7000000
        weight: 10
        size_l: 20
        size_h: 30
        size_w: 30
        product: "Iphone 14 Promax"
        product_value: 40000000
        shipping_fee: 18000
        insurance_fee: 20000
        is_insurance_fee: true
        receiver_name: "Tran Van A"
        receiver_phone: "090 9332 982"
        receiver_address : "81 Hoàng Minh Giám"
        receiver_port_code : "R2587289"
        receiver_address_level_1: "Phường 4"
        receiver_address_level_2: "Quận Phú Nhuận"
        receiver_address_level_3: "Thành Phố Hồ Chí Minh"
        sender_phone: "0922736283"
        sender_name: "Test TRG"
        sender_address: "5/34 Thủ Khoa Huân"
        sender_port_code: "R2587289"
        sender_address_level_1: "Phường Long Bình"
        sender_address_level_2: "Quận 9"
        sender_address_level_3: "Thành Phố Hồ Chí Minh"
        status: "Waiting_for_pickup"
        notes: "Hàng dễ vỡ, xin nhẹ tay"
        epod_pickup_success: "https://luatacc.com/wp-content/uploads/2022/02/chu-ky-la-gi.png"


    GetAllPackages:
      title: Get All Packages
      type: array
      properties:
        code:
          title: 3PL LM Code
          type: string
        package_code:
          title: Hiko code
          type: string
        tracking_code:
          title: 3PL Tracking code
          type: string
        port_code:
          title: Port code
          type: string
        cod:
          title: Cod
          type: integer
        weight:
          title: Weight
          type: integer
        size_l:
          title: Size length
          type: integer
        size_h:
          title: Size height
          type: integer
        size_w:
          title: Size width
          type: integer
        product:
          title: Product
          type: string
        product_value:
          title: Product value
          type: integer
        receiver_name:
          title: Receiver's name
          type: string
        receiver_phone:
          title: Receiver's phone
          type: string
        receiver_address:
          title: Receiver address
          type: string
        receiver_port_code:
          title: Receiever's port code
          type: string
        receiver_address_level_1:
          title: Receiever address lv1
          type: string
        receiver_address_level_2:
          title: Receiever address lv2
          type: string
        receiver_address_level_3:
          title: Receiever address lv3
          type: string
        sender_phone:
          title: Sender phone
          type: string
        sender_email:
          title: Sender email
          type: string
        sender_name:
          title: Sender name
          type: string
        sender_address:
          title: Sender's address
          type: string
        sender_port_code:
          title: Sender's port code
          type: string
        sender_address_level_1:
          title: Sender's address lv1
          type: string
        sender_address_level_2:
          title: Sender's address lv2
          type: string
        sender_address_level_3:
          title: Sender's address lv3
          type: string
        status:
          title: Status
          type: string
        notes:
          title: Note
          type: string
        epod_pickup_success:
          title: epod package pickup successful
          type: string
      example:
      - code: "PKG2210897312"
        package_code: "PKG10897312"
        tracking_number: "LMP0170517004VNA"
        cod: 7000000
        weight: 10
        size_l: 20
        size_h: 30
        size_w: 30
        product: "Iphone 14 Promax"
        product_value: 30000000
        receiver_name: "Tran Van A"
        receiver_phone: "090 9332 982"
        receiver_address: "81 Hoàng Minh Giám"
        receiver_port_code : "R2587289"
        receiver_address_level_1: "Phường 4"
        receiver_address_level_2: "Quận Phú Nhuận"
        receiver_address_level_3: "Thành Phố Hồ Chí Minh"
        sender_phone: "0922736283"
        sender_name: "Test TRG"
        sender_address: "5/34 Thủ Khoa Huân"
        sender_port_code : "R2587289"
        sender_address_level_1: "Phường Long Bình"
        sender_address_level_2: "Quận 9"
        sender_address_level_3: "Thành Phố Hồ Chí Minh"
        status: "In_pickup"
        notes: "Hàng dễ vỡ, xin nhẹ tay"
        epod_pickup_success: "https://luatacc.com/wp-content/uploads/2022/02/chu-ky-la-gi.png"
      - code: "PKG2210897312"
        package_code: "PKG10897312"
        tracking_number: "LMP0170517004VNA"
        cod: 7000000
        weight: 10
        size_l: 20
        size_h: 30
        size_w: 30
        product: "Nệm"
        product_value: 3000500
        receiver_name: "Tran Van B"
        receiver_phone: "090 9332 982"
        receiver_address: "81 Hoàng Minh Giám"
        receiver_port_code : "R2587289"
        receiver_address_level_1: "Phường 4"
        receiver_address_level_2: "Quận Phú Nhuận"
        receiver_address_level_3: "Thành Phố Hồ Chí Minh"
        sender_phone: "0922736283"
        sender_email: "Hiko@yopmail.com"
        sender_name: "Test TRG"
        sender_address: "5/34 Thủ Khoa Huân"
        sender_port_code : "R2587289"
        sender_address_level_1: "Phường 5"
        sender_address_level_2: "Quận 4"
        sender_address_level_3: "Thành Phố Hồ Chí Minh"
        status: "In_delivery"
        notes: "Hàng dễ vỡ, xin nhẹ tay"
        epod_pickup_success: NULL

    ProfileRes:
      title: Profile
      type: object
      properties:
        id:
          title: id
          type: string
        name:
          title: name
          type: string
        phone:
          title: phone
          type: string
        email:
          title: email
          type: string
      example:
        id: "SEL00004793"
        name: "Nguyen van A"
        phone: "090000000"
        email: "nguyenvana@example.vn"



    CreatePackageError:
      title: CreatePackageError
      type: object
      properties:
        error:
          $ref: '#/components/schemas/ValidationCreatePackage'

    ValidationCreatePackage:
      title: ValidationCreatePackage
      type: object
      properties:
        cod:
          type: string
          example: "The COD field is required."
        weight:
          type: string
          example: "The Weight field is required."
        size_l:
          type: string
          example: "The Length field is required."
        size_h:
          type: string
          example: "The Height field is required."
        size_w:
          type: string
          example: "The Width field is required."
        receiver_name:
          type: string
          example: "The Receiver's name field is required."
        receiver_phone:
          type: string
          example: "The Receiver's phone field is required."
        receiver_address:
          type: string
          example: "The Receiver's address field is required."
        sender_name:
          type: string
          example: "The Sender's name field is required."
        sender_phone:
          type: string
          example: "The Sender's phone field is required."
        sender_email:
          type: string
          example: "The Sender's email field is required."
        sender_address:
          type: string
          example: "The Sender's address field is required."
        product:
          type: string
          example: "The Sender's product field is required."
        notes:
          type: string
          example: "The Sender's notes field is required."

    PackageStatuses:
      title: PackageStatuses
      required:
        - id
        - code
      type: object
      properties:
        id:
          title: Id
          type: integer
        code:
          title: Code
          type: string
      example:
        - code: "Waiting_for_approval"
        - code: "Planned_for_pickup"
        - code: "In_pickup"
        - code: "Pickup_failed_attempt"
        - code: "Pickup_successful"
        - code: "Pickup_failed"
        - code: "Waiting_for_linehaul"
        - code: "Waiting_for_delivery"
        - code: "In_delivery"
        - code: "Delivery_failed_attempt"
        - code: "Delivery_successful"
        - code: "Delivery_failed"
        - code: "Waiting_for_return"
        - code: "In_return"
        - code: "Return_failed_attempt"
        - code: "Return_failed"
        - code: "Returned"
        - code: "Lost_collection_approved"
        - code: "Shop_lost_claimed"
        - code: "3pl_cancelled"
        - code: "Cancel_failed"
        - code: "Shop_canceled"
        - code: "Cancelled"

    WardOut:
      title: WardOut
      type: object
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
      example:
        - id: 1
          name: "Phường 3"
        - id: 2
          name: "Phường 4"
        - id: 3
          name: "Phường 5"

    DistrictOut:
      title: DistrictOut
      type: object
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
      example:
        - id: 1
          name: "Quận 1"
        - id: 2
          name: "Quận 2"
        - id: 3
          name: "Quận 3"

    ThreePLAddress:
      title: ThreePLAddress
      type: object
      properties:
        id:
          title: Id
          type: integer
        province:
          title: province
          type: string
        district:
          title: district
        ward:
          title: district
        port_code:
          title: port_code
      example:
        - province: "Thành Phố Hồ Chí Minh"
          district: "Quận 1"
          ward: "Phường Đa Kao"
          port_code: "R2587289"
        - province: "Thành Phố Hồ Chí Minh"
          district: "Quận 1"
          ward: "Phường Bến Nghé"
          port_code: "R2587255"

    BodyInsuranceFees:
      title: GetInsuranceFees
      type: object
      required:
        - product_value
      properties:
        product_value:
          title: product value > 30000000
          type: integer
          example: 4000000

    ResponseInsuranceFee:
      title: Insurance Fee
      properties:
        insurance_fee:
          type: integer
          default: 20000

    BodyGetShippingFees:
      title: GetShippingFees

      required:
        - sender_port_code
        - receiver_port_code
        - weight
      type: object
      properties:
        seller_code:
          title: Seller code
          type: string
          description: Use seller code when not authentication
        sender_port_code:
          title: Sender's port code
          type: string
          default: "R0001"
        receiver_port_code:
          title: Receiver's port code
          type: string
          default: "R0042"
        weight:
          title: Weight - gram
          type: integer
          default: 200
      example:
        - sender_port_code: "R0001"
          receiver_port_code: "R0001"
          weight: "200"

    ResponseGetShippingFees:
      title: GetShippingFeeOut
      type: object
      properties:
        shipping_fee:
          type: integer
          default: 27000
        min_est_leadtime:
          type: integer
          default: 1
        max_est_leadtime:
          type: integer
          default: 2
        max_est_return_leadtime:
          type: integer
          default: 8

    ResponseGetShippingFeesError:
      title: GetShippingFeeError
      type: object
      properties:
        success:
          type: boolean
          default: false
        message:
          type: string
          default: "Error message"
        data:
          type: string
          default: ""

    ResponsePackageHistory:
      title: PackageHistory
      type: object
      properties:
        receiver_name:
          type: string
          default: "Nguyễn Văn A"
        receiver_phone:
          type: string
          default: "0972312231"
        receiver_address:
          type: string
          default: "132A Nguyễn Trọng Tuyển"
        receiver_address_level_1:
          type: string
          default: "Phường 8"
        receiver_address_level_2:
          type: string
          default: "Quận Phú Nhuận"
        receiver_address_level_3:
          type: string
          default: "Thành Phố Hồ Chí Minh"
        sender_name:
          type: string
          default: "Nguyễn Văn A"
        sender_phone:
          type: string
          default: "0972312231"
        sender_address:
          type: string
          default: "132A Nguyễn Trọng Tuyển"
        sender_address1_level_1:
          type: string
          default: "Phường 8"
        sender_address_level_2:
          type: string
          default: "Quận Phú Nhuận"
        sender_address_level_3:
          type: string
          default: "Thành Phố Hồ Chí Minh"
        status:
          type: string
          default: "Delivered"
        cod:
          type: integer
          default: 100000
        audits:
          type: array
          properties:
            status:
              type: string
            courier:
              type: string
            current_hub:
              type: string
            updated_at:
              type: string
              title: updated_at
          example:
            - status: "In_pickup"
              courier: ""
              current_hub: ""
              updated_at: "2022-08-16T06:13:33.000000Z"
            - status: "In_Delivery"
              courier: "Tài Xe a"
              current_hub: "OMS"
              updated_at: "2022-08-16T06:13:33.000000Z"
            - status: "Delivered"
              courier: "Tài Xe a"
              current_hub: "OMS"
              updated_at: "2022-08-16T06:13:33.000000Z"

    ResponseTrue:
      title: ResponseTrue
      type: object
      properties:
        success:
          title: success
          type: boolean
          example: true

    ResponseFailed:
      title: ResponseFailed
      type: object
      properties:
        success:
          title: success
          type: boolean
          example: false

    ResponseAwb:
      title: File PDF
      properties:
        link:
          title: link
          type: string
          example: link-to-file-awb

  securitySchemes:
    APIKeyHeader:
      type: apiKey
      description: Login with email and password
      in: header
      name: Authorization
